# -*- coding: utf-8 -*-
"""
/***************************************************************************
 catuloader
                                 A QGIS plugin
 This plugin aims to download Internet shp files and add them as a vector layer on QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-15
        copyright            : (C) 2025 by Catulo Axel
        email                : catuloaxel.mat@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load catuloader class from file catuloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .catuloader import catuloader
    return catuloader(iface)
